-----------------------------------------------------------------
-- Autogenerated by Thrift
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE BangPatterns #-}
{-# OPTIONS_GHC -fno-warn-unused-imports#-}
{-# OPTIONS_GHC -fno-warn-overlapping-patterns#-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns#-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
module Facebook.Logdevice.Thrift.Admin.Admin.Types () where
import qualified Facebook.FB303.Fb303.Types as Facebook.FB303.Fb303
import qualified
       Facebook.Logdevice.Thrift.AdminCommand.AdminCommands.Types
       as Facebook.Logdevice.Thrift.AdminCommand.AdminCommands
import qualified
       Facebook.Logdevice.Thrift.ClusterMembership.ClusterMembership.Types
       as Facebook.Logdevice.Thrift.ClusterMembership.ClusterMembership
import qualified Facebook.Logdevice.Thrift.Common.Common.Types
       as Facebook.Logdevice.Thrift.Common.Common
import qualified
       Facebook.Logdevice.Thrift.Exceptions.Exceptions.Types
       as Facebook.Logdevice.Thrift.Exceptions.Exceptions
import qualified Facebook.Logdevice.Thrift.LogTree.Logtree.Types
       as Facebook.Logdevice.Thrift.LogTree.Logtree
import qualified
       Facebook.Logdevice.Thrift.Maintenance.Maintenance.Types
       as Facebook.Logdevice.Thrift.Maintenance.Maintenance
import qualified Facebook.Logdevice.Thrift.Nodes.Nodes.Types
       as Facebook.Logdevice.Thrift.Nodes.Nodes
import qualified Facebook.Logdevice.Thrift.Safety.Safety.Types
       as Facebook.Logdevice.Thrift.Safety.Safety
import qualified Facebook.Logdevice.Thrift.Settings.Settings.Types
       as Facebook.Logdevice.Thrift.Settings.Settings
import qualified Prelude as Prelude
import qualified Thrift.CodegenTypesOnly as Thrift